### PR TITLE
Minimize requirements

### PR DESCRIPTION
**Pull request by theMarix**
Removes the extraneous Mock requirement and allows to use the client wrapper without installing the full Devpi server package.

I also pip-compiled the requirements while I was at it…

### CODE REVIEW

**Comment by StephanErb** [comment]
LGTM!

Any chance we can get rid of the nose dep in `setup_requires` as well? This would be useful if anyone is installing from a source distribution.

**Comment by theMarix** [comment]
Nose dependency is only required to enable nose integration into setup.py. As we explicitly use the `nosetests` command to run the tests we could skip that.

**Comment by cjw296** [comment]
This breaks use of DevpiServer, which appears to be part of the public api of devpi-plumber:

```python
from devpi_plumber.server import prefill_serverdir, DevpiServer
```

**Comment by theMarix** [comment]
You should still get the feature via the extra test requirement, e.g. `pip install devpi-plumber[test]`.

**Comment by cjw296** [comment]
Sure, but I'd have thought that was for if I want to *test* devpi-plumber. I'm just looking to use devpi-plumber to test my code...

**Comment by theMarix** [comment]
At least from my point of view devpi-plumber has two parts:
1. It wraps the client API, allowing to use the client from Python code instead of the command line
2. It provides a harness for the Devpi Server to be used in tests of user code.
That's why the additional requirements for the server are wrapped in an extra requirement called test. But it might be that choice of name was not that self-explaining after all. Maybe server would have been better.

**Pull request merged**
