### PR TITLE
Add client_cert parameter to DevpiClient and DevpiCommandWrapper

### PR DESCRIPTION
**Pull request by hlawrenz**
This adds support for the devpi client's --client-cert parameter so that an SSL certificate may be used to authenticate with the server.

### CODE REVIEW

**Comment by hlawrenz** [comment]
Two notes on the check failures:
1. The test failure seems to be caused by the coverage library using a u prefix on a string (unsupported in 3.2). Presumably this is a change since the last build.
2. I didn't add a test for the added code so the coverage decreased. I can do so but the complexity I think it'll add to the testing may not be worth it.

**Comment by theMarix** [comment]
Could you please rebase your patch? We are no longer testing on 3.2, so the build error should be gone.

**Comment by hlawrenz** [comment]
New in the last commit you'll find new tests and some minor refactoring of the DevpiCommandWrapper class to aid those tests. In order to avoid setting up a devpi server with client cert support and such, I made it so I could monkey patch DevpiCommandWrapper._execute method to just return the command that would be executed. This way the tests can just compare the generated command against the expected command. I think this will be helpful in working on other issues such as <https://github.com/blue-yonder/devpi-builder/issues/94>. Let me know if you want anything changed.

**Comment by theMarix** [comment]
Thanks, that seems to be a good way to test that. I'll try to get a release out today.

**Pull request merged**
