### PR TITLE
Add a contextmanager wrapper which does logon/logoff.

### PR DESCRIPTION
**Pull request by criemen**
This is useful to do things like
with DevpiClient(url) as devpi:
     devpi.create_user(...)
     with devpi.user_session(...):
           # do stuff as user

### CODE REVIEW

**Comment by Corni** [comment]
This is a very good point, thanks!

**Comment by StephanErb** [comment]
Please also add a changelog entry :)

**Comment by StephanErb** [comment]
@Corni needs a rebase :) 

Would also be awesome if you could add a test for the code line without coverage. It is not really super important but dropping from 100% coverage needs a good excuse :)

**Comment by Corni** [comment]
This includes the test, the rebase on master and a .gitattributes so that CHANGELOG entries do not produce conflicts anymore.

**Pull request merged**
